[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "prettyplot"
version = "0.1.0"
description = "Publication-ready plotting with a clean, modular API"
readme = "README.md"
requires-python = ">=3.9"
license = {text = "MIT"}
authors = [
    {name = "Jorge Botas", email = "jorge.botas@example.com"}
]
keywords = ["plotting", "visualization", "matplotlib", "seaborn", "publication"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Scientific/Engineering :: Visualization",
]

dependencies = [
    "matplotlib>=3.5.0",
    "seaborn>=0.12.0",
    "numpy>=1.21.0",
    "pandas>=1.3.0",
    "scipy>=1.7.0",
    "matplotlib-venn>=0.11.0",
]

[project.optional-dependencies]
dev = [
    "pytest>=7.0.0",
    "pytest-cov>=4.0.0",
    "black>=23.0.0",
    "mypy>=1.0.0",
    "ruff>=0.1.0",
]

[project.urls]
Homepage = "https://github.com/jorgebotas/prettyplot"
Documentation = "https://github.com/jorgebotas/prettyplot"
Repository = "https://github.com/jorgebotas/prettyplot"
Issues = "https://github.com/jorgebotas/prettyplot/issues"

[tool.hatch.build.targets.wheel]
packages = ["src/prettyplot"]

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--cov=prettyplot --cov-report=html --cov-report=term-missing"

[tool.black]
line-length = 88
target-version = ["py39"]
include = '\.pyi?$'

[tool.ruff]
line-length = 88
target-version = "py39"
select = ["E", "F", "I", "N", "W"]

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = false
